# Generated by Django 6.0.6 on 2026-06-22 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المستر/المدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(choices=[('meme', '🤡 ميمز'), ('reel', '🎬 ريل فيديو'), ('tiktok', '📱 تيك توك للمستر'), ('carousel', '📸 كاروسيل'), ('design', '🎨 ديزاين'), ('ai', '🤖 ذكاء اصطناعي'), ('interactive', '❓ تفاعل')], default='meme', max_length=20)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', '🎥 محتاج تصوير'), ('progress', '🎨 قيد العمل'), ('ready', '🟢 جاهز للنشر')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.teacher')),
            ],
            options={
                'ordering': ['week', 'id'],
            },
        ),
    ]
